### ISSUE TITLE
Colorama not being pulled in by easy_install

### ISSUE THREAD

**Issue by JamesHarrison** [JamesHarrison/openob#1]
After a basic install with easy_install:

```
pi@raspberrypi ~ $ openob
    Traceback (most recent call last):
      File "/usr/local/bin/openob", line 5, in <module>
        pkg_resources.run_script('OpenOB==2.3', 'openob')
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
        execfile(script_filename, namespace, namespace)
      File "/usr/local/lib/python2.7/dist-packages/OpenOB-2.3-py2.7.egg/EGG-INFO/scripts/openob", line 7, in <module>
        from openob.manager import Manager
      File "/usr/local/lib/python2.7/dist-packages/OpenOB-2.3-py2.7.egg/openob/manager.py", line 3, in <module>
        from openob.rtp.tx import RTPTransmitter
      File "/usr/local/lib/python2.7/dist-packages/OpenOB-2.3-py2.7.egg/openob/rtp/tx.py", line 7, in <module>
        from colorama import Fore, Back, Style
    ImportError: No module named colorama
```

**Comment by m4mad** [comment]
:/
