### ISSUE TITLE
 Namespace Gst not available

### ISSUE THREAD

**Issue by endriuman** [JamesHarrison/openob#41]
sudo openob 192.168.0.10 test-rx-node test-link rx
Traceback (most recent call last):
  File "/usr/local/bin/openob", line 4, in <module>
    __import__('pkg_resources').run_script('OpenOB==4.0.2', 'openob')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/OpenOB-4.0.2-py2.7.egg/EGG-INFO/scripts/openob", line 8, in <module>

  File "build/bdist.linux-armv7l/egg/openob/node.py", line 4, in <module>
  File "build/bdist.linux-armv7l/egg/openob/rtp/tx.py", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available

**Comment by JamesHarrison** [comment]
Docs now mention this, so closing.
