### ISSUE TITLE
server does not connect

### ISSUE THREAD

**Issue by endriuman** [JamesHarrison/openob#42]
This message always appears to me.

**### **redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.****

**Comment by endriuman** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/openob", line 61, in <module>
    link_config.set_from_argparse(opts)
  File "/usr/local/lib/python2.7/dist-packages/openob/link_config.py", line 89, in set_from_argparse
    self.set("multicast", opts.multicast)
  File "/usr/local/lib/python2.7/dist-packages/openob/link_config.py", line 51, in set
    self.redis.set(scoped_key, value)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1394, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 113, in encode
    raise DataError("Invalid input of type: 'bool'. Convert to a "
redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.

**Comment by PeterPancorbo** [comment]
Having same problem. Could you solve it?

Thanks!

**Comment by djsakisd** [comment]
@PeterPancorbo @endriuman  Can you try to dowgrade the redis version using pip and try again.. It's an issue most probably with redis python library rather than openob code.

Had the same problem with a few machines when upgraded the redis python.

**Comment by jonty-comp** [comment]
It looks like this is due to a new check in redis > 3.0.0, released in November - I'll see what I can do.

**Comment by PeterPancorbo** [comment]
Thanks so much!! All working fine now.

**Comment by JamesHarrison** [comment]
Finally cut a new release so this should now be sorted.
