### ISSUE TITLE
redis.exceptions.DataError: Invalid input of type: 'bool'.

### ISSUE THREAD

**Issue by clair892** [JamesHarrison/openob#45]
cant start TX test mode. RX test looks start normaly.
how do i fix it?
(my IP 192.168.0.4)

OS(from /etc/os-release)
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
~~~~~~~~
pi@raspberrypi:~ $ openob 192.168.0.4 test-tx-node test-link tx 192.168.0.4
2019-01-12 02:59:40,772 - openob.link.test-link.config - INFO - Connecting to configuration host 192.168.0.4
Traceback (most recent call last):
  File "/usr/local/bin/openob", line 4, in <module>
    __import__('pkg_resources').run_script('OpenOB==4.0.2', 'openob')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/OpenOB-4.0.2-py2.7.egg/EGG-INFO/scripts/openob", line 81, in <module>

  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 89, in set_from_argparse
  File "build/bdist.linux-armv7l/egg/openob/link_config.py", line 51, in set
  File "build/bdist.linux-armv7l/egg/redis/client.py", line 1394, in set
  File "build/bdist.linux-armv7l/egg/redis/client.py", line 754, in execute_command
  File "build/bdist.linux-armv7l/egg/redis/connection.py", line 619, in send_command
  File "build/bdist.linux-armv7l/egg/redis/connection.py", line 659, in pack_command
  File "build/bdist.linux-armv7l/egg/redis/connection.py", line 113, in encode
redis.exceptions.DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.
pi@raspberrypi:~ $

**Comment by JamesHarrison** [comment]
Should now be sorted in 4.0.3.
