### ISSUE TITLE
Crash log for Openob receiver

### ISSUE THREAD

**Issue by sarexpert** [JamesHarrison/openob#51]
Using Openob rx with redis running on the tx server, piped over spiped on internet with two ISP companies in loop.
Link had run for about a week before crashing.
Hopefully this is the right venue to report this bug.

Transmitter command line:  (was still running)
 /usr/bin/python /usr/local/bin/openob 127.0.0.1 studio-node STL-link tx -a jack -jn STL -l 1 --dtx -j 900 -b 96 -jp stereo_tool:fm 199.193.vvv.xxx

Command line of receiver that crashed: 
 /usr/local/bin/openob 127.0.0.1 FMTX-node STL-link rx -a jack -jn ob-STL -jp On_Air:in_2.

Error output:

2020-01-17 07:04:58,183 - openob.node.FMTX-node.link.STL-link.rx - CRITICAL - No data received for 3 seconds!
2020-01-17 07:05:03,099 - openob.node.FMTX-node.link.STL-link.rx - INFO - Receiving stereo audio transmission
2020-01-20 04:19:48,435 - openob.node.FMTX-node.link.STL-link.rx - CRITICAL - No data received for 3 seconds!
2020-01-20 04:19:48,435 - openob.node.FMTX-node.link.STL-link.rx - CRITICAL - Shutting down receiver for restart
2020-01-20 04:19:48,517 - openob.node.FMTX-node.link.STL-link - INFO - Waiting for transmitter capabilities...
2020-01-20 04:19:53,520 - openob.node.FMTX-node.link.STL-link - ERROR - Unknown exception thrown - please report this as a bug! Error while reading from socket: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/node.py", line 56, in run_link
    caps = link_config.blocking_get("caps")
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/link_config.py", line 43, in blocking_get
    value = self.get(key)
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/link_config.py", line 63, in get
    value = self.redis.get(scoped_key)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 310, in read_response
    response = self._buffer.readline()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 242, in readline
    self._read_from_socket()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 209, in _read_from_socket
    (ex.args,))
ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')
Traceback (most recent call last):
  File "/usr/local/bin/openob", line 87, in <module>
    node.run_link(link_config, audio_interface)
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/node.py", line 56, in run_link
    caps = link_config.blocking_get("caps")
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/link_config.py", line 43, in blocking_get
    value = self.get(key)
  File "/home/broadcast/.local/lib/python2.7/site-packages/openob/link_config.py", line 63, in get
    value = self.redis.get(scoped_key)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 1332, in get
    return self.execute_command('GET', name)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/client.py", line 853, in parse_response
    response = connection.read_response()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 310, in read_response
    response = self._buffer.readline()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 242, in readline
    self._read_from_socket()
  File "/home/broadcast/.local/lib/python2.7/site-packages/redis/connection.py", line 209, in _read_from_socket
    (ex.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

[1]+  Exit 1                  /usr/local/bin/openob 127.0.0.1 FMTX-node STL-link rx -a jack -jn ob-STL -jp On_Air:in_2.

**Comment by JamesHarrison** [comment]
The connection reset by peer error is usually an authentication failure or Redis version mismatch. Redis isn't used in the latest version in any case, so closing.
